#链路信息存储到mysal或者mq防止重启信息消失
zipkin:
  storage:
    type: mysql
spring:
  application:
    name: zipkin-server
  datasource:
    url: jdbc:mysql://localhost:3306/spring-cloud-zipkin?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  sleuth:
    enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/
server:
  port: 9411
