eureka:
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/
server:
  port: 5000
spring:
  application:
    name: gateway-service
  zipkin:
    base-url: http://peer1:9411
  sleuth:
    sampler:
#      100%概率将链路的数据上传给zipkin
      percentage: 1.0
zuul:
  routes:
    api-a:
      path: /user-api/**
      serviceId: user-service
