server:
  port: 5000

eureka:
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oauth2?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: service-auth
security:
  oauth2:
    resource:
#      固定写法
      filter-order: 3
