#  从本地读取配置文件
spring:
  profiles:
    active: native
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
    bus:
      enabled: true
      trace:
        enabled: true
  rabbitmq:
    host: 192.168.1.6
    port: 5672
    username: guest
    password: guest
management:
  security:
    enabled: false
server:
  port: 8762

#git远程配置
#spring:
#  application:
#    name: config-server
#  cloud:
#    config:
#      server:
#        git:
#          uri: git-address
#          search-paths: //远程仓库文件夹地址
#          username:
#          password:
##            仓库分支名
#      label: master
#server:
#  port: 8761



eureka:
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/

