server:
  port: 5001
  context-path: /uaa
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oauth2?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: service-hi
security:
  oauth2:
    resource:
      user-info-uri: http://peer1:5000/uaa/users/current
    client:
      client-secret: 123456
      id: service-hi
      access-token-uri:  http://peer1:5000/uaa/oauth/token
      grant-type: client_credentials,password
      scope: server

