eureka:
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/
server:
  port: 8762
spring:
  application:
    name: admin-client
logging:
  file: "logs/eureka-client-one.log"
management:
  security:
    enabled: false
